### ISSUE TITLE
[FEAT] Add ability to change case of environment variables in envfile

### ISSUE THREAD

**Issue by russellseymour** [taskctl/taskctl#102]
When Terraform runs on Windows, any environment variables that are set using the `TF_VAR_` prefix are case insensitive. However on Linux the variables are sensitive, so if they have been set in UPPERCASE and the TF is referencing the using lowercase, the values will not be set.

This feature is to add configuration to modify the environment variables as they are added to the file. The structure for this will be similar to the following:

```
envfile:
   modify:
      - pattern: ^TF_VAR_(.*)
        mode: lower
```
