### ISSUE TITLE
Interpolate variables

### ISSUE THREAD

**Issue by trntv** [taskctl/taskctl#78]
Interpolate tasks's variables to allow such configs:
```yaml
tasks:
  image:bluid:
    command:
      - docker build -t {{ .Registry }}/foo:{{ .Tag }} .
      - docker push {{ .Registry }}/foo:{{ .Tag }}
    variables:
      Tag: '{{ .Args | default "latest" }}'
      Registry: registry.example.com
```
