### ISSUE TITLE
Define environment variables using a property file

### ISSUE THREAD

**Issue by hetesiistvan** [taskctl/taskctl#82]
In my case I use ```taskctl``` to deploy an application to different environments. This includes most of the steps of the lifecycle starting from building the application to K8s deployment.

Quite some steps do require environment-specific information, like server URL, connection string, etc... In some cases those information needs to be passed as a command-line argument, in other cases they are required for templating.

The values which are environment specific are stored in properties files, e.g. like ```test.properties```:
```
DB_URL=...
SELECTED_REGION=...
SMTP_SERVER=...
```
This is really convenient to maintain but requires a workaround ATM to be used with ```taskctl```.

## Feature proposal

Individual environment variables can be used ATM like this:
```
  build:
    command: go build -o bin/app ./...
    env: 
      GOOS: linux
      GOARCH: amd64
```
(example from the documentation)

Using environment property files would look like the following:
```
  build:
    command: go build -o bin/app ./...
    env_file: 
      build.properties
```
Where ```build.properties``` contains:
```
GOOS: linux
GOARCH: amd64
```

This would be already a great help.

If the name of the environment file could contain variable like ``` "{{ .ArgsList[1] }}.properties" it would be quite perfect. 🚀 

Many thanks for considering this!
